# Generated by Django 4.1.3 on 2022-11-10 17:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('account_managers', '0001_initial'),
        ('client_managers', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('client', models.CharField(max_length=255, unique=True)),
                ('account_manager', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='account_manager_clients', to='account_managers.accountmanager')),
                ('client_manager', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='client_manager_clients', to='client_managers.clientmanager')),
            ],
            options={
                'verbose_name': 'Client',
                'verbose_name_plural': 'Clients',
            },
        ),
    ]
